In [2]:
import numpy as np

In [3]:
original_x = np.array([3, 9, 11, 5, 2]).astype(float);
original_y = np.array([1, 8, 11, 4, 3]).astype(float);
original_x, original_y

(array([ 3.,  9., 11.,  5.,  2.]), array([ 1.,  8., 11.,  4.,  3.]))

In [4]:
x = original_x.copy()
y = original_y.copy()
x, y

(array([ 3.,  9., 11.,  5.,  2.]), array([ 1.,  8., 11.,  4.,  3.]))

In [6]:
n = len(x)
n

5

In [8]:
sum_y = np.sum(y)
sum_x = np.sum(x)
sum_x, sum_y

(30.0, 27.0)

In [9]:
mean_y = sum_y / n
mean_x = sum_x / n
mean_x, mean_y

(6.0, 5.4)

In [10]:
for i in range(n):
    x[i] = x[i] - mean_x
    y[i] = y[i] - mean_y
x, y

(array([-3.,  3.,  5., -1., -4.]), array([-4.4,  2.6,  5.6, -1.4, -2.4]))

In [11]:
sumOfProductOfDeviationsOf_x_and_y = 0
sumOfSquareOfDeviationsOf_x = 0
for i in range(n):
    sumOfProductOfDeviationsOf_x_and_y += (x[i] * y[i])
    sumOfSquareOfDeviationsOf_x += (x[i] * x[i])
sumOfProductOfDeviationsOf_x_and_y, sumOfSquareOfDeviationsOf_x    

(60.0, 60.0)

In [12]:
slope = sumOfProductOfDeviationsOf_x_and_y / sumOfSquareOfDeviationsOf_x
slope

1.0

In [13]:
intercept = mean_y - (slope * mean_x)
intercept

-0.5999999999999996

In [15]:
y_pred = intercept + (slope * original_x)
y_pred

array([ 2.4,  8.4, 10.4,  4.4,  1.4])

In [16]:
original_x, y_pred

(array([ 3.,  9., 11.,  5.,  2.]), array([ 2.4,  8.4, 10.4,  4.4,  1.4]))